# Generated by Django 2.2.1 on 2019-05-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='img/course_logo/', verbose_name='Фото курса')),
                ('little_description', models.CharField(max_length=200, verbose_name='Небольшое описание курса на главной странице')),
                ('description', models.TextField(verbose_name='Полное описание курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_one', models.CharField(max_length=200, verbose_name='Название первой недели')),
                ('description_week_one', models.TextField(verbose_name='Описание первой недели')),
                ('week_second', models.CharField(max_length=200, verbose_name='Название второй недели')),
                ('description_week_second', models.TextField(verbose_name='Описание второй недели')),
                ('week_third', models.CharField(max_length=200, verbose_name='Название третьей недели')),
                ('description_week_third', models.TextField(verbose_name='Описание третьей недели')),
                ('week_fourth', models.CharField(max_length=200, verbose_name='Название четвертой недели')),
                ('description_week_fourth', models.TextField(verbose_name='Описание четвертой недели')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDay', models.CharField(db_index=True, max_length=200, verbose_name='Название урока')),
                ('day', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание Урока')),
                ('url_video', models.URLField()),
                ('nameCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='course.Course', verbose_name='Курс')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
